name: selfsuper
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=h8cf3c4a_0
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py39hb9d737c_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - almosthere=2.0.2=h46c0cb4_1
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.3.0=h27087fc_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bgen=4.1.3=ha0ad84f_0
  - bgen-reader=4.0.8=py39hf3d152e_0
  - blas=2.106=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - blosc=1.21.3=hafa529b_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotli-python=1.0.9=py39h5a03fae_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.6.1=hf91038e_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - captum=0.5.0=0
  - cbgen=1.0.1=py39hb9d737c_2
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - codecarbon=2.1.4=pyh1a96a4e_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - contourpy=1.0.6=py39hf939315_0
  - cryptography=39.0.0=py39h079d5ae_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py39hb9d737c_1
  - dash=2.7.1=pyhd8ed1ab_0
  - dash-bootstrap-components=1.3.0=pyhd8ed1ab_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_1
  - dash-table=5.0.0=pyhd8ed1ab_1
  - dask=2022.12.1=pyhd8ed1ab_0
  - dask-core=2022.12.1=pyhd8ed1ab_0
  - debugpy=1.6.4=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - distributed=2022.12.1=pyhd8ed1ab_0
  - dnspython=2.3.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - eigen=3.4.0=h4bd325d_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - fire=0.4.0=pyh44b312d_0
  - flask=1.1.2=pyh9f0ad1d_0
  - flask-compress=1.13=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py39hb9d737c_1
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.3.3=py39hb9d737c_0
  - fsspec=2022.11.0=pyhd8ed1ab_0
  - future=0.18.2=pyhd8ed1ab_6
  - fuzzywuzzy=0.18.0=pyhd8ed1ab_0
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.30=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.51.1=py39h8c60046_0
  - h5py=3.7.0=nompi_py39h817c9c5_102
  - hdf5=1.12.2=nompi_h4df4325_101
  - heapdict=1.0.1=py_0
  - humanize=4.4.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py39hfcd4fa2_6
  - imageio=2.23.0=pyhfa7a67d_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.1=pyhd8ed1ab_1
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.19.4=pyh210e3f2_0
  - ipython=8.7.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=5.1.1=py39hf3d152e_0
  - jupyter_server=1.23.4=pyhd8ed1ab_0
  - jupyterlab=3.3.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.17.0=pyhd8ed1ab_0
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=3.0=h9c3ff4c_0
  - levenshtein=0.20.9=py39h227be39_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.10.1=h166bdaf_0
  - libblas=3.9.0=6_mkl
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=6_mkl
  - libcurl=7.87.0=hdc1c0ab_0
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgrpc=1.51.1=h30feacc_0
  - libhwloc=2.8.0=h32351e8_1
  - libiconv=1.17=h166bdaf_0
  - libitk=5.3.0=hcedbc38_0
  - liblapack=3.9.0=6_mkl
  - liblapacke=3.9.0=6_mkl
  - libllvm11=11.1.0=he0ac6c6_5
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=hc85c160_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - libzopfli=1.0.3=h9c3ff4c_0
  - lime=0.2.0.1=pyh9f0ad1d_0
  - llvm-openmp=15.0.6=he0ac6c6_0
  - llvmlite=0.39.1=py39h7d9a04d_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.2.0=py39h724f13c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_2
  - matplotlib-base=3.6.2=py39hf9fd14e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2020.4=h726a3e6_304
  - monai=1.0.1=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py39hf939315_1
  - multidict=6.0.4=py39h72bdee0_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-connector-python=8.0.31=py39hfa0bd35_2
  - mysql-libs=8.0.32=hd7da12d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.7=pyhd8ed1ab_0
  - nbconvert-core=7.2.7=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=2.8.6=pyhd8ed1ab_0
  - nibabel=3.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numba=0.56.4=py39h61ddf18_0
  - numpy=1.23.5=py39h3d75532_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.7=h0b41bf4_1
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.5.2=py39h4661b88_0
  - pandoc=2.19.2=h32600fe_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py39hae2aec6_1
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - plotly=5.11.0=pyhd8ed1ab_1
  - pluggy=1.0.0=pyhd8ed1ab_5
  - pooch=1.6.0=pyhd8ed1ab_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - promise=2.3=py39hf3d152e_7
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=4.21.12=py39h227be39_0
  - psutil=5.9.4=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pydicom=2.3.1=pyh1a96a4e_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pynndescent=0.5.8=pyh1a96a4e_0
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.2=py39hb9d737c_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.2.0=pyhd8ed1ab_2
  - python=3.9.15=hba424b6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-levenshtein=0.20.9=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-lightning=1.6.4=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.3.0=py39h2ae25f5_2
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=24.0.1=py39headdf64_1
  - rapidfuzz=2.13.7=py39h227be39_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-image=0.19.3=py39h1832856_1
  - scikit-learn=1.2.0=py39h86b2a18_0
  - scipy=1.8.1=py39h8ba3f38_2
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentry-sdk=1.12.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py39hb9d737c_1
  - setuptools=59.5.0=py39hf3d152e_0
  - shortuuid=1.0.11=pyhd8ed1ab_0
  - simpleitk=2.2.1=py39hdaa313e_1
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=hbd366e4_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h2ae25f5_2
  - tbb=2021.7.0=h924138e_1
  - tblib=1.7.0=pyhd8ed1ab_0
  - tenacity=8.1.0=pyhd8ed1ab_0
  - tensorboard=2.11.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39h3ccb8fc_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - termcolor=2.1.1=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - texttable=1.6.7=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.10.10=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchaudio=0.11.0=py39_cu113
  - torchio=0.18.86=pyhd8ed1ab_0
  - torchmetrics=0.11.0=pyhd8ed1ab_0
  - torchvision=0.12.0=py39_cu113
  - tornado=6.2=py39hb9d737c_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.8.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - umap-learn=0.5.3=py39hf3d152e_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wandb=0.12.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - wrapt=1.14.1=py39hb9d737c_1
  - xarray=2022.12.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.2=py39hb9d737c_0
  - yaspin=2.2.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_8
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=h6239696_4
  - pip:
    - antlr4-python3-runtime==4.9.3
    - cachetools==4.2.4
    - carbontracker==1.1.6
    - geocoder==1.38.1
    - google-auth==1.35.0
    - hydra-core==1.2.0
    - icd10-cm==0.0.5
    - liac-arff==2.5.0
    - lightly==1.2.22
    - lightly-utils==0.0.2
    - lightning-bolts==0.5.0
    - matplotlib-venn==0.11.7
    - minio==7.1.9
    - omegaconf==2.2.2
    - opencv-python==4.6.0.66
    - openml==0.12.2
    - pyarrow==8.0.0
    - ratelim==0.1.6
    - simple-icd-10==2.0.1
    - tabpfn==0.1.8
    - torch-tb-profiler==0.4.0
    - xgboost==1.7.4
    - xmltodict==0.13.0
